title: Works in Various States of Progress
description: Things I wrote that I think might be worth sharing (at some point.)
theme: just-the-docs

url: https://menckend.github.io/writing

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
